name: Generate and Push Docs to Wiki

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
            repository: ${{ github.repository }}.wiki
            path: wiki

      - name: Install Python and docmd
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install docmd
        run: pip install docmd

      - name: Create MD files from PyPlaque docstrings
        run: |
          ls
          pip install -e .
          mkdir -p docs
          docmd PyPlaque.experiment --out docs
          docmd PyPlaque.phenotypes --out docs
          docmd PyPlaque.specimen --out docs
          docmd PyPlaque.utils --out docs
          docmd PyPlaque.view --out docs
          cd docs

      - name: Copy generated docs to wiki
        run: |
          cp -v *.md wiki/

      - name: Commit and push to Wiki
        run: |
          cd ../../
          rm -rf docs
