name: Generate and Push Docs to Wiki

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
            repository: ${{ github.repository }}.wiki
            path: wiki
      
      - name: Checkout PyPlaque repo
        uses: actions/checkout@v4
        with:
            repository: ${{ github.repository }}
            path: PyPlaque

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install docmd
        run: pip install docmd

      - name: Create MD files from PyPlaque docstrings
        run: |
          ls
          cd PyPlaque
          pip install -e .
          mkdir -p docs
          docmd PyPlaque.experiment --out docs
          docmd PyPlaque.phenotypes --out docs
          docmd PyPlaque.specimen --out docs
          docmd PyPlaque.utils --out docs
          docmd PyPlaque.view --out docs

      - name: Copy generated docs to wiki
        run: |
          cp -v docs/*.md ../wiki/
          rm -rf docs

      - name: Run script to update wiki
        run: |
          cd ../wiki
          git add .
          git commit -m "Updated wiki with a new page"
          git push
